name       : seccure
version    : 0.5
release    : 1
source     :
    - http://point-at-infinity.org/seccure/seccure-0.5.tar.gz : 6566ce4afea095f83690b93078b910ca5b57b581ebc60e722f6e3fe8e098965b
license    : LGPL-3.0
component  : security.crypto
summary    : The seccure toolset implements a selection of asymmetric algorithms based on elliptic curve cryptography (ECC).
description: |
    The seccure toolset implements a selection of asymmetric algorithms based on elliptic curve cryptography (ECC). In particular it offers public key encryption / decryption, signature generation / verification and rudimentary key establishment.
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/share/man/man1
    %make_install
